app:
  telegram-token: ${TELEGRAM-TOKEN}
  scrapper-topic-name: link-updates

scrapper-client-config:
  baseUrl: ${BASE_URL:http://localhost:8080}
  attempts: ${ATTEMPTS:2}
  duration: ${DURATION:5s}
  retry-policy: ${BACK-OFF-STRATEGY:constant} # values: constant, linear, exponential
  retry-codes:
    - 404

kafka:
  consumer:
    bootstrapServers: localhost:9092
    groupId: link-tracker
    autoOffsetReset: latest
    maxPollIntervalMs: 300_000
    enableAutoCommit: false
    concurrency: 1
  producer:
    bootstrapServers: localhost:9092
    clientId: todolist-backend
    acksMode: all
    deliveryTimeout: 60s
    lingerMs: 1_000
    batchSize: 100_000
    maxInFlightPerConnection: 5
    enableIdempotence: true # to handle specific retry errors
bucket:
  refill-size: 5
  refill-interval: 1 #minutes
  capacity: 5

bucket-cache:
  max-size: 100
  expiration-time: 10 #minutes
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

