/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "https://www.jooq.org",
                "jOOQ version:3.18.6"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChatLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer linkId;
    private Long chatId;

    public ChatLink() {
    }

    public ChatLink(ChatLink value) {
        this.linkId = value.linkId;
        this.chatId = value.chatId;
    }

    @ConstructorProperties({"linkId", "chatId"})
    public ChatLink(
            @NotNull Integer linkId,
            @NotNull Long chatId
    ) {
        this.linkId = linkId;
        this.chatId = chatId;
    }

    /**
     * Getter for <code>CHAT_LINK.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Integer getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>CHAT_LINK.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>CHAT_LINK.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>CHAT_LINK.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long chatId) {
        this.chatId = chatId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChatLink other = (ChatLink) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        } else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        } else if (!this.chatId.equals(other.chatId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatLink (");

        sb.append(linkId);
        sb.append(", ").append(chatId);

        sb.append(")");
        return sb.toString();
    }
}
